# Generated by Django 3.2.9 on 2023-02-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.CharField(max_length=100)),
                ('time', models.FloatField()),
                ('data', models.TextField()),
            ],
        ),
    ]
