# Generated by Django 4.1 on 2023-01-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testtable",
            fields=[
                ("post_number", models.AutoField(primary_key=True, serialize=False)),
                ("contents", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
