# Generated by Django 4.1 on 2023-01-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0002_testtable"),
    ]

    operations = [
        migrations.DeleteModel(name="Testtable",),
    ]
