# Generated by Django 4.1 on 2023-01-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbs", "0006_board_users"),
    ]

    operations = [
        migrations.DeleteModel(name="Test",),
    ]
