# Generated by Django 4.1.5 on 2023-01-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('post_number', models.AutoField(primary_key=True, serialize=False)),
                ('contents', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
