# Generated by Django 4.1 on 2023-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_remove_answer_author_id_remove_question_author_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
